spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.21.128/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates/
    request-context-attribute: request
    suffix: .ftl
    content-type: text/html
    cache: false
    charset: UTF-8
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
  redis:
    host: 192.168.21.128
    port: 6379

server:
  servlet:
    context-path: /sell
wechat:
  mpAppId:
  mpAppSecret:
  openAppid:
  opAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl:

projecturl:
  wechatMpAuthorize:
  wechatOpenAuthorize:
  sell: